// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIHJpUD0Yc74IJcP4PbPJNmpLMV21TGU4',
    appId: '1:828276794494:web:e4bb7546f6d59179dda42f',
    messagingSenderId: '828276794494',
    projectId: 'flutteraula04',
    authDomain: 'flutteraula04.firebaseapp.com',
    storageBucket: 'flutteraula04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLisuq9tWPg8mhfdieUnYBHRfNq2maaKw',
    appId: '1:828276794494:android:7fd482cf4b735416dda42f',
    messagingSenderId: '828276794494',
    projectId: 'flutteraula04',
    storageBucket: 'flutteraula04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANa-HFivnq6jI4mPzWBOOX57mJ0_SF83E',
    appId: '1:828276794494:ios:a5abedcf57ff1eefdda42f',
    messagingSenderId: '828276794494',
    projectId: 'flutteraula04',
    storageBucket: 'flutteraula04.firebasestorage.app',
    iosBundleId: 'br.com.fabioalvaro.flutteraula04',
  );
}
